name: matrix-whatsapp-bridged
adopt-info: mautrix-whatsapp
summary: A Matrix-WhatsApp puppeting bridge based on whatsmeow.
description: |
      To use with matrix-synapse-bridged
grade: stable
base: core22

confinement: strict

# Make /var/lib/synapse inside the snap point to $SNAP_DATA directory as you
# can't use the $SNAP_DATA variable in config yaml files
layout:
    /var/log/mautrix-whatsapp:
      bind: $SNAP_DATA

apps:
  mautrix-whatsapp:
    command: bin/mautrix-whatsapp
    
parts:
  mautrix-whatsapp:
    plugin: go
    source-type: git
    source: https://github.com/mautrix/whatsapp.git
    build-snaps:
      - go
    stage-packages:
      - libolm-dev
    build-packages:
      - libolm-dev
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
